apiVersion: v1
kind: Service
metadata:
  labels:
    app: kni
  name: kni
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31536
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kni
