apiVersion: v1
kind: Service
metadata:
  labels:
    app: kni
  name: kni
spec:
  type: ClusterIP
  selector:
    app: kni
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080

   
